# SQLite version 3.x
#   gem 'activerecord-jdbcsqlite3-adapter'
#
# Configure Using Gemfile
# gem 'activerecord-jdbcsqlite3-adapter'
#

development:
  adapter: postgresql
  encoding: unicode
  database: fundwise_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: fundwise_dev
  pool: 5
  host: localhost

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5